import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Search, ShoppingBag, UserRound, ArrowUpRight, Menu, X, Plus, Minus, ChevronDown, SlidersHorizontal, Heart, Sparkles, LayoutDashboard, Store, ShieldCheck, Check } from 'lucide-react'
import { products, brands, brandDetails, money } from './data'
import { endpoint } from './api/client'
import './styles.css'
import './brand-pages.css'
import './checkout.css'

function App(){
 const [catalogue,setCatalogue]=useState(products); const [category,setCategory]=useState('All'); const [query,setQuery]=useState(''); const [sort,setSort]=useState('newest'); const [filterOpen,setFilterOpen]=useState(false); const [cart,setCart]=useState(()=>JSON.parse(localStorage.getItem('drip-cart')||'[]')); const [cartOpen,setCartOpen]=useState(false); const [checkoutOpen,setCheckoutOpen]=useState(false); const [menu,setMenu]=useState(false); const [mode,setMode]=useState('shop'); const [selectedBrand,setSelectedBrand]=useState(null); const [user,setUser]=useState(null);
 useEffect(()=>{ endpoint.products.list({sort,limit:20}).then(result=>{ if(Array.isArray(result?.data)&&result.data.length) setCatalogue(result.data.map(normalizeProduct)) }).catch(()=>{}) },[sort])
 useEffect(()=>{ endpoint.auth.me().then(setUser).catch(()=>{}) },[])
 const filtered=useMemo(()=>{const result=catalogue.filter(p=>(category==='All'||p.category===category)&&(!query||`${p.name} ${p.brand}`.toLowerCase().includes(query.toLowerCase())));return [...result].sort((a,b)=>sort==='price_asc'?a.price-b.price:sort==='price_desc'?b.price-a.price:0)},[catalogue,category,query,sort]);
 const add=(p)=>{const next=[...cart,p];setCart(next);localStorage.setItem('drip-cart',JSON.stringify(next));setCartOpen(true)};
 const remove=(i)=>{const next=cart.filter((_,idx)=>idx!==i);setCart(next);localStorage.setItem('drip-cart',JSON.stringify(next))};
 const total=cart.reduce((a,p)=>a+p.price,0);
 return <div className="app">
  <div className="ticker"><span>DRIP DROP 01 — FREE SHIPPING OVER PKR 10,000</span><span>SELL YOUR CULTURE / KEEP 85%</span><span>NEW IN EVERY FRIDAY</span></div>
    <header className="header"><button className="icon-btn mobile-only" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><a className="logo" onClick={()=>{setMode('shop');setCategory('All')}}>DRIP<span>.</span></a><nav className={menu?'nav open':'nav'}><button onClick={()=>{setMode('shop');setCategory('All');setMenu(false)}}>SHOP</button><button onClick={()=>{setMode('shop');setCategory('Tops');setMenu(false)}}>TOPS</button><button onClick={()=>{setMode('shop');setCategory('Bottoms');setMenu(false)}}>BOTTOMS</button><button onClick={()=>{setMode('shop');setCategory('Outerwear');setMenu(false)}}>OUTERWEAR</button><button onClick={()=>{setMode(user?'sell':'auth');setMenu(false)}}>SELL ON DRIP</button></nav><div className="header-actions"><label className="search"><Search size={17}/><input placeholder="Search pieces" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘K</kbd></label><button className="icon-btn" title="Account" onClick={()=>setMode(user?(user.role==='admin'?'admin':'account'):'auth')}><UserRound size={19}/></button><button className="bag-btn" onClick={()=>setCartOpen(true)}><ShoppingBag size={19}/><b>{cart.length}</b></button></div></header>
  {mode==='shop'&&<main>
   <section className="hero"><div className="hero-copy"><p className="eyebrow lime">NEW COLLECTION / 2026</p><h1>Wear what's<br/><em>next.</em></h1><p className="hero-text">Discover independent fashion brands, curated in one place.</p><button className="lime-btn" onClick={()=>document.getElementById('catalogue').scrollIntoView({behavior:'smooth'})}>SHOP NOW <ArrowUpRight size={18}/></button></div><div className="hero-art"><div className="hero-circle"></div><div className="hero-word">DRIP</div><div className="hero-sticker">EST.<br/>2026</div></div></section>
   <section className="brand-rail"><div className="section-kicker">THE MALL <span>06 INDEPENDENT LABELS</span></div><div className="brands">{brands.map((b,i)=><button className="brand" key={b} onClick={()=>{setSelectedBrand(b);setMode('brand')}}><span>0{i+1}</span><strong>{b}</strong><ArrowUpRight size={16}/></button>)}</div></section>
   <section className="category-strip">{['All','Tops','Bottoms','Outerwear','Headwear'].map(c=><button className={category===c?'active':''} onClick={()=>setCategory(c)} key={c}>{c}<sup>{c==='All'?catalogue.length:catalogue.filter(p=>p.category===c).length}</sup></button>)}</section>
  <section className="catalogue" id="catalogue"><div className="catalogue-head"><div><p className="eyebrow">CURATED FOR YOU</p><h2>{category==='All'?'New arrivals':category}</h2></div><div className="catalogue-tools"><button onClick={()=>setFilterOpen(!filterOpen)}><SlidersHorizontal size={16}/> FILTERS</button><label className="sort-select"><ChevronDown size={16}/><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort products"><option value="newest">SORT: NEWEST</option><option value="price_asc">PRICE: LOW TO HIGH</option><option value="price_desc">PRICE: HIGH TO LOW</option></select></label></div></div>{filterOpen&&<div className="filter-panel"><span>FILTER BY CATEGORY</span>{['All','Tops','Bottoms','Outerwear','Headwear'].map(c=><button className={category===c?'active':''} onClick={()=>{setCategory(c);setFilterOpen(false)}} key={c}>{c}</button>)}</div>}<div className="product-grid">{filtered.map(p=><ProductCard key={p.id} p={p} onAdd={add}/>)}</div></section>
   <section className="sell-banner"><div><p className="eyebrow lime">FOR THE INDEPENDENT</p><h2>Your label<br/><span>belongs here.</span></h2></div><div className="sell-info"><p>Get your pieces in front of people who get it. 50 slots, 85% of every sale, zero gatekeeping.</p><button className="outline-btn" onClick={()=>setMode('sell')}>START SELLING <ArrowUpRight size={17}/></button></div></section>
  </main>}
    {mode==='sell'&&<SellerWorkspace onBack={()=>setMode('shop')}/>} {mode==='account'&&<CustomerWorkspace onBack={()=>setMode('shop')}/>} 
    {mode==='auth'&&<AuthScreen onLogin={next=>{setUser(next);setMode(next.role==='admin'?'admin':next.role==='seller'?'sell':'account')}} onBack={()=>setMode('shop')}/>} 
    {mode==='admin'&&<AdminDashboard onBack={()=>setMode('shop')} onLogout={()=>{endpoint.auth.logout().catch(()=>{});sessionStorage.removeItem('drip_access_token');setUser(null);setMode('shop')}}/>}
  {mode==='brand'&&<BrandPage name={selectedBrand} onBack={()=>setMode('shop')} onAdd={add}/>} 
  <footer><div className="logo">DRIP<span>.</span></div><p>Independent fashion, on your terms.</p><div><a>Instagram</a><a>WhatsApp</a><a>Terms</a></div></footer>
  {cartOpen&&<><div className="scrim" onClick={()=>setCartOpen(false)}></div><aside className="cart"><div className="cart-head"><h2>Your bag <span>{cart.length}</span></h2><button className="icon-btn" onClick={()=>setCartOpen(false)}><X/></button></div>{cart.length===0?<div className="empty"><ShoppingBag size={36}/><p>Your bag is empty.</p><button className="lime-btn" onClick={()=>setCartOpen(false)}>KEEP SHOPPING</button></div>:<><div className="cart-items">{cart.map((p,i)=><div className="cart-item" key={i}><img src={p.image}/><div><small>{p.brand}</small><strong>{p.name}</strong><span>{money(p.price)}</span></div><button onClick={()=>remove(i)}><X size={15}/></button></div>)}</div><div className="cart-bottom"><div><span>Subtotal</span><b>{money(total)}</b></div><div><span>Shipping</span><span>Calculated at checkout</span></div><button className="lime-btn full" onClick={()=>{setCartOpen(false);setCheckoutOpen(true)}}>CHECKOUT <ArrowUpRight size={17}/></button><small className="fee">Platform fee is included in seller pricing, not added to your total.</small></div></>}</aside></>}
  {checkoutOpen&&<CheckoutPanel user={user} cart={cart} total={total} onClose={()=>setCheckoutOpen(false)} onLogin={()=>{setCheckoutOpen(false);setMode('auth')}} onComplete={()=>{setCheckoutOpen(false);setCart([]);localStorage.removeItem('drip-cart')}}/>}
 </div>
}
function AuthScreen({onLogin,onBack}){
 const [register,setRegister]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget));try{const result=register?await endpoint.auth.register(data):await endpoint.auth.login(data);if(register){setRegister(false);setError(result?.message||'Account created. Check your email before signing in.')}else{sessionStorage.setItem('drip_access_token',result.access_token);onLogin(result.user)}}catch(err){setError(err.message)}finally{setBusy(false)}}
 return <main className="auth-page"><button className="back" onClick={onBack}>← BACK TO DRIP</button><section className="auth-panel"><div className="auth-copy"><p className="eyebrow lime">DRIP MEMBERS</p><h1>{register?'Join the drop.':'Welcome back.'}</h1><p>{register?'Create your account and keep every independent label in reach.':'Sign in to manage orders, products, payouts, and your DRIP profile.'}</p></div><form className="auth-form" onSubmit={submit}>{register&&<div className="form-row"><label>First name<input name="first_name" required minLength="2"/></label><label>Last name<input name="last_name" required minLength="2"/></label></div>}<label>Email<input type="email" name="email" required autoComplete="email"/></label><label>Password<input type="password" name="password" required autoComplete={register?'new-password':'current-password'}/></label>{register&&<label>Phone <span className="hint">optional</span><input name="phone" placeholder="03001234567"/></label>}{error&&<p className="form-error">{error}</p>}<button className="lime-btn full" disabled={busy}>{busy?'PLEASE WAIT…':register?'CREATE ACCOUNT':'SIGN IN'} <ArrowUpRight size={17}/></button><button type="button" className="text-btn" onClick={()=>{setRegister(!register);setError('')}}>{register?'Already have an account? Sign in':'New to DRIP? Create an account'}</button></form></section></main>
}
function CheckoutPanel({user,cart,total,onClose,onLogin,onComplete}){
 const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [coupon,setCoupon]=useState(''); const [discount,setDiscount]=useState(0); const [couponMessage,setCouponMessage]=useState('');
 const applyCoupon=async()=>{if(!coupon)return;try{const result=await endpoint.orders.validateCoupon({code:coupon,subtotal:total});setDiscount(result.discount_amount||0);setCouponMessage(result.message||'Coupon applied')}catch(err){setCouponMessage(err.message)}};
 const submit=async e=>{e.preventDefault();if(!user){onLogin();return}setBusy(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget));const payload={shipping_address:{recipient_name:data.recipient_name,phone:data.phone,street:data.street,city:data.city,province:data.province},payment_method:data.payment_method,coupon_code:coupon||null,notes:data.notes||null};try{const order=await endpoint.orders.create(payload);if(data.payment_method!=='cod')await endpoint.payments.initiate({order_id:order.order_id});onComplete()}catch(err){setError(err.message)}finally{setBusy(false)}};
 return <div className="modal-layer"><div className="checkout-modal"><div className="cart-head"><div><p className="eyebrow lime">SECURE CHECKOUT</p><h2>Finish your order.</h2></div><button className="icon-btn" onClick={onClose}><X/></button></div>{!user&&<div className="form-error">Sign in is required before checkout. <button className="text-btn" onClick={onLogin}>SIGN IN</button></div>}<form className="checkout-form" onSubmit={submit}><div className="form-row"><label>Recipient name<input name="recipient_name" required/></label><label>Phone<input name="phone" required placeholder="03001234567"/></label></div><label>Street address<input name="street" required/></label><div className="form-row"><label>City<input name="city" required/></label><label>Province<input name="province" required/></label></div><label>Payment method<select name="payment_method" defaultValue="payfast"><option value="payfast">PayFast</option><option value="card">Card</option><option value="cod">Cash on delivery</option></select></label><div className="coupon-row"><input value={coupon} onChange={e=>setCoupon(e.target.value)} placeholder="Coupon code"/><button type="button" className="outline-btn" onClick={applyCoupon}>APPLY</button></div>{couponMessage&&<small>{couponMessage}</small>}{error&&<p className="form-error">{error}</p>}<div className="checkout-total"><span>Total</span><strong>{money(Math.max(0,total-discount))}</strong></div><button className="lime-btn full" disabled={busy}>{busy?'PROCESSING…':'PLACE ORDER'} <ArrowUpRight size={17}/></button></form></div></div>
}
function AdminDashboard({onBack,onLogout}){
 const [dashboard,setDashboard]=useState(null); const [sellers,setSellers]=useState(null); const [orders,setOrders]=useState(null); const [error,setError]=useState('');
 useEffect(()=>{Promise.all([endpoint.admin.dashboard('month'),endpoint.admin.sellers({status:'all',page:1,per_page:8}),endpoint.admin.orders({page:1,per_page:8})]).then(([d,s,o])=>{setDashboard(d);setSellers(s);setOrders(o)}).catch(err=>setError(err.message))},[])
 const stats=dashboard?[['GMV',money(dashboard.total_gmv)],['Platform revenue',money(dashboard.platform_revenue)],['Orders',dashboard.total_orders],['Pending payouts',dashboard.pending_payouts]]:[];
 return <main className="dashboard admin-dashboard"><div className="dash-top"><div><button className="back" onClick={onBack}>← BACK TO SHOP</button><p className="eyebrow lime">CONTROL ROOM / ADMIN</p><h1>Run the marketplace.</h1></div><button className="outline-btn" onClick={onLogout}>SIGN OUT</button></div>{error&&<div className="form-error">{error}</div>}<div className="stat-grid">{stats.length?stats.map(([label,value])=><Stat key={label} label={label} value={value} delta="LIVE FROM API"/>):<Stat label="Loading overview" value="…" delta=""/>}</div><div className="admin-grid"><section className="panel"><div className="panel-head"><h3>Seller review queue</h3><span>{sellers?.total??'—'} total</span></div>{sellers?.data?.length?sellers.data.map(s=><div className="admin-row" key={s.id}><div><b>{s.brand_name}</b><small>{s.product_count} products · {s.status}</small></div><strong>{money(s.total_gmv)}</strong><span className="status-pill">{s.status}</span></div>):<div className="empty small"><ShieldCheck size={28}/><p>Seller data is loading.</p></div>}</section><section className="panel"><div className="panel-head"><h3>Latest orders</h3><span>{orders?.total??'—'} total</span></div>{orders?.data?.length?orders.data.map(order=><div className="admin-row" key={order.id}><div><b>#{order.order_number}</b><small>{order.customer_name} · {order.payment_method}</small></div><strong>{money(order.total)}</strong><span className="status-pill">{order.status}</span></div>):<div className="empty small"><LayoutDashboard size={28}/><p>Order data is loading.</p></div>}</section></div></main>
}
function CustomerWorkspace({onBack}){
 const [user,setUser]=useState(null); const [orders,setOrders]=useState(null); const [error,setError]=useState('');
 useEffect(()=>{Promise.all([endpoint.auth.me(),endpoint.orders.list({page:1})]).then(([me,orderData])=>{setUser(me);setOrders(orderData)}).catch(err=>setError(err.message))},[])
 return <main className="dashboard"><div className="dash-top"><div><button className="back" onClick={onBack}>← BACK TO SHOP</button><p className="eyebrow lime">YOUR ACCOUNT</p><h1>{user?`Welcome, ${user.first_name||'back'}.`:'Your account.'}</h1></div><button className="outline-btn" onClick={()=>endpoint.auth.logout().then(()=>{sessionStorage.removeItem('drip_access_token');onBack()})}>SIGN OUT</button></div>{error&&<p className="form-error">{error}</p>}<div className="customer-panels"><section className="panel"><div className="panel-head"><h3>Recent orders</h3><span>{orders?.pagination?.total??orders?.total??'—'} total</span></div>{orders?.data?.length?orders.data.map(order=><div className="admin-row" key={order.id}><div><b>#{order.order_number}</b><small>{order.status} · {order.payment_method}</small></div><strong>{money(order.total)}</strong></div>):<div className="empty small"><Check size={28}/><p>No orders yet.</p><button className="outline-btn" onClick={onBack}>BROWSE THE DROP</button></div>}</section><section className="panel"><div className="panel-head"><h3>Profile</h3><UserRound size={18}/></div><p>{user?.email||'Loading profile…'}</p><p>{user?.phone||'Add a phone number at checkout.'}</p></section></div></main>
}
function SellerWorkspace({onBack}){
 const [profile,setProfile]=useState(null); const [dashboard,setDashboard]=useState(null); const [productsData,setProductsData]=useState(null); const [wallet,setWallet]=useState(null); const [error,setError]=useState(''); const [addProductOpen,setAddProductOpen]=useState(false);
 useEffect(()=>{Promise.all([endpoint.seller.profile(),endpoint.seller.dashboard('month'),endpoint.seller.products({status:'all',page:1}),endpoint.seller.wallet()]).then(([p,d,items,w])=>{setProfile(p);setDashboard(d);setProductsData(items);setWallet(w)}).catch(err=>setError(err.message))},[])
 return <main className="dashboard"><div className="dash-top"><div><button className="back" onClick={onBack}>← BACK TO SHOP</button><p className="eyebrow lime">SELLER STUDIO</p><h1>{profile?.brand_name||'Your label.'}</h1></div><div className="dash-actions"><button className="lime-btn" onClick={()=>setAddProductOpen(true)}>ADD PRODUCT <Plus size={17}/></button><button className="outline-btn" onClick={onBack}>EXIT STUDIO</button></div></div>{error&&<p className="form-error">{error}</p>}<div className="stat-grid"><Stat label="Gross revenue" value={dashboard?money(dashboard.gross_revenue):'…'} delta="LIVE"/><Stat label="Orders" value={dashboard?.order_count??'…'} delta="THIS PERIOD"/><Stat label="Available balance" value={wallet?money(wallet.available_balance):'…'} delta="WALLET"/><Stat label="Products" value={dashboard?.product_count??productsData?.total??'…'} delta="CATALOGUE"/></div><div className="dash-grid"><section className="panel"><div className="panel-head"><h3>Product catalogue</h3><span>{productsData?.total??'—'} total</span></div>{productsData?.data?.length?productsData.data.map(product=><div className="admin-row" key={product.id}><div><b>{product.name}</b><small>{product.price} · {product.is_published?'published':'draft'}</small></div><span className="status-pill">{product.is_published?'LIVE':'DRAFT'}</span></div>):<div className="empty small"><Store size={28}/><p>No products yet.</p></div>}</section><section className="panel"><div className="panel-head"><h3>Wallet</h3><span>{wallet?.pending_balance?money(wallet.pending_balance):'No pending balance'}</span></div><p>Available: <strong>{wallet?money(wallet.available_balance):'Loading…'}</strong></p><button className="outline-btn" onClick={()=>alert('Withdrawal management is available once a bank account is added.')}>REQUEST WITHDRAWAL</button></section></div>{addProductOpen&&<AddProductPanel onClose={()=>setAddProductOpen(false)} onCreated={product=>{setProductsData(current=>current?{...current,data:[product,...(current.data||[])],total:(current.total||0)+1}:current);setAddProductOpen(false)}}/>}</main>
}
function AddProductPanel({onClose,onCreated}){
 const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const submit=async event=>{event.preventDefault();setBusy(true);setError('');const form=Object.fromEntries(new FormData(event.currentTarget));const payload={name:form.name,description:form.description,price:Number(form.price),sale_price:form.sale_price?Number(form.sale_price):null,is_published:false,variants:[{size_type:form.size_type,size_value:form.size_value,colour:form.colour,stock:Number(form.stock),sku:form.sku||null}]};try{const product=await endpoint.seller.createProduct(payload);onCreated(product)}catch(err){setError(err.message)}finally{setBusy(false)}};
 return <div className="modal-layer"><section className="checkout-modal product-form-modal"><div className="cart-head"><div><p className="eyebrow lime">SELLER STUDIO / NEW PRODUCT</p><h2>Add a product.</h2></div><button className="icon-btn" onClick={onClose}><X/></button></div><form className="checkout-form" onSubmit={submit}><label>Product name<input name="name" required minLength="2" maxLength="200" placeholder="Orbit Heavyweight Tee"/></label><label>Description<textarea name="description" required minLength="10" maxLength="5000" rows="4" placeholder="Describe the piece, fit, and materials."/></label><div className="form-row"><label>Price (PKR)<input name="price" type="number" min="100" max="500000" required/></label><label>Sale price <span className="hint">optional</span><input name="sale_price" type="number" min="100" max="500000"/></label></div><div className="form-row"><label>Size type<select name="size_type" defaultValue="one_size"><option value="one_size">One size</option><option value="alpha">Alpha</option><option value="numeric">Numeric</option></select></label><label>Size value<input name="size_value" required placeholder="M or One Size"/></label></div><div className="form-row"><label>Colour<input name="colour" required placeholder="Black"/></label><label>Stock<input name="stock" type="number" min="0" required defaultValue="1"/></label></div><label>SKU <span className="hint">optional</span><input name="sku" maxLength="100" placeholder="VOID-TEE-001"/></label>{error&&<p className="form-error">{error}</p>}<button className="lime-btn full" disabled={busy}>{busy?'CREATING…':'CREATE PRODUCT'} <ArrowUpRight size={17}/></button></form></section></div>
}
function normalizeProduct(p){ return { ...p, id:p.id||p.product_id, name:p.name||p.title, brand:p.brand_name||p.brand?.name||'INDEPENDENT LABEL', price:Math.round((p.sale_price??p.price??0)/100), oldPrice:p.price&&p.sale_price?Math.round(p.price/100):undefined, category:p.category_name||p.category||'Tops', badge:p.is_new?'NEW':p.on_sale?'SALE':undefined, rating:p.rating??4.8, colors:p.colours||p.colors||['#1a1a1a','#dfff00'], image:p.primary_image||p.image||p.images?.[0]?.url||products[0].image } }
function BrandPage({name,onBack,onAdd}){const info=brandDetails[name]||brandDetails['VOID FORM'];const items=products.filter(p=>p.brand===name);return <main className="brand-page"><button className="back" onClick={onBack}>← BACK TO DRIP</button><section className="brand-hero" style={{'--brand-accent':info.accent}}><img src={info.image} alt={`${name} campaign`}/><div className="brand-hero-overlay"><p className="eyebrow">DRIP / BRAND STOREFRONT</p><h1>{name}</h1><p>{info.tagline}</p></div></section><section className="brand-intro"><div><p className="eyebrow">THE LABEL</p><h2>{name}<br/><span>{info.tagline}</span></h2></div><div><p>{info.story}</p><button className="outline-btn">CONTACT BRAND <ArrowUpRight size={16}/></button></div></section><section className="brand-stats"><div><b>✓ VERIFIED BRAND</b><span>Quality checked by DRIP</span></div><div><b>{info.products}</b><span>Products</span></div><div><b>{info.orders}</b><span>Successful orders</span></div><div><b>★ {info.rating}</b><span>Average rating</span></div><div><b>7 DAYS</b><span>Return policy</span></div></section><section className="brand-products"><div className="catalogue-head"><div><p className="eyebrow">THE COLLECTION</p><h2>Shop {name}</h2></div><button className="outline-btn">SORT: NEWEST <ChevronDown size={15}/></button></div>{items.length?<div className="product-grid">{items.map(p=><ProductCard key={p.id} p={p} onAdd={onAdd}/>)}</div>:<div className="brand-empty"><p>This brand is preparing its first DRIP collection.</p><button className="lime-btn" onClick={onBack}>EXPLORE ALL BRANDS</button></div>}</section></main>}
function ProductCard({p,onAdd}){const [liked,setLiked]=useState(false);return <article className="product"><div className="product-image"><img src={p.image} alt={p.name}/>{p.badge&&<span className="badge">{p.badge}</span>}<button className={liked?'heart liked':'heart'} onClick={()=>setLiked(!liked)}><Heart size={17} fill={liked?'currentColor':'none'}/></button><button className="quick-add" onClick={()=>onAdd(p)}><Plus size={17}/> QUICK ADD</button></div><div className="product-meta"><div><small>{p.brand}</small><h3>{p.name}</h3></div><strong>{money(p.price)}</strong></div><div className="product-foot"><span>★★★★★ <i>{p.rating}</i></span><div className="swatches">{p.colors.map(c=><i style={{background:c}} key={c}/>)}</div></div></article>}
function Dashboard({type,onBack}){const seller=type==='seller'; return <main className="dashboard"><div className="dash-top"><div><button className="back" onClick={onBack}>← BACK TO SHOP</button><p className="eyebrow lime">{seller?'SELLER STUDIO':'YOUR ACCOUNT'}</p><h1>{seller?'Good morning, VOID FORM.':'Welcome back.'}</h1></div><button className="lime-btn">{seller?'ADD PRODUCT':'EDIT PROFILE'} <ArrowUpRight size={17}/></button></div>{seller?<><div className="stat-grid"><Stat label="Revenue this month" value="PKR 184,250" delta="+18.4%"/><Stat label="Orders" value="42" delta="+7 this week"/><Stat label="Net earnings" value="PKR 156,612" delta="85% payout"/><Stat label="Slots used" value="18 / 50" delta="32 available"/></div><div className="dash-grid"><div className="panel"><div className="panel-head"><h3>Recent orders</h3><button>VIEW ALL →</button></div>{['#DRP-1048','#DRP-1047','#DRP-1043','#DRP-1039'].map((o,i)=><div className="order-row" key={o}><span className="order-dot"></span><div><b>{o}</b><small>{['Orbit Heavyweight Tee × 1','Asphalt Cargo Trouser × 2','Static Racing Jacket × 1','Acid Washed Hoodie × 1'][i]}</small></div><strong>{['PKR 4,200','PKR 15,600','PKR 12,500','PKR 6,900'][i]}</strong><em className={i===2?'green':''}>{['PROCESSING','SHIPPED','DELIVERED','PROCESSING'][i]}</em></div>)}</div><div className="panel slots"><div className="panel-head"><h3>Slot meter</h3><span>36%</span></div><div className="meter"><i style={{width:'36%'}}></i></div><p><b>18</b> published <span>/</span> <b>50</b> total slots</p><button className="outline-btn">BUY EXTRA SLOTS</button></div></div></>:<div className="customer-panels"><div className="panel"><div className="panel-head"><h3>Recent orders</h3><button>VIEW ALL →</button></div><div className="empty small"><Check size={28}/><p>Your orders will appear here.</p><button className="outline-btn" onClick={onBack}>BROWSE THE DROP</button></div></div><div className="panel quick-links"><h3>Quick links</h3><button><Heart size={17}/> Wishlist <span>0 items</span></button><button><Store size={17}/> Saved addresses <span>0 saved</span></button><button><ShieldCheck size={17}/> Account settings <ArrowUpRight size={17}/></button></div></div>}</main>}
function Stat({label,value,delta}){return <div className="stat"><small>{label}</small><strong>{value}</strong><span>{delta}</span></div>}
createRoot(document.getElementById('root')).render(<App/>)
