"""
app/models/base.py
──────────────────
SQLAlchemy 2.x declarative base and reusable mixins.

All models extend Base + the relevant mixins.
Never put business logic in models — services own that.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from typing import Any

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """
    Declarative base for all ORM models.
    Configures PostgreSQL UUID type mapping.
    """
    type_annotation_map = {
        uuid.UUID: UUID(as_uuid=True),
    }

    def to_dict(self) -> dict[str, Any]:
        """Utility for debugging — returns all column values as a dict."""
        return {
            col.name: getattr(self, col.name)
            for col in self.__table__.columns
        }

    def __repr__(self) -> str:
        pk = getattr(self, "id", "?")
        return f"<{self.__class__.__name__} id={pk}>"


# ── Mixins ────────────────────────────────────────────────────────────────────

class UUIDPrimaryKeyMixin:
    """UUID primary key, generated by the database (gen_random_uuid())."""
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """Automatic created_at and updated_at timestamps (UTC)."""
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class SoftDeleteMixin:
    """
    Soft delete support.
    Records are never hard-deleted; deleted_at is set instead.
    All queries must filter WHERE deleted_at IS NULL.
    """
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        index=True,
    )

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None

    def soft_delete(self) -> None:
        """Mark this record as deleted."""
        self.deleted_at = datetime.now(UTC)

    def restore(self) -> None:
        """Undo a soft delete."""
        self.deleted_at = None


class AuditMixin(TimestampMixin, SoftDeleteMixin):
    """Combines timestamps + soft delete. Used by most domain models."""
    pass